/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springworkspace;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@Setter
// @NoArgsConstructor // 빈 생성자 > 초기화 작업 x > final 지정되면 오류
@AllArgsConstructor // 생성자 생성
@RequiredArgsConstructor // final 지정된 항목에 대해서만 생성자 생성
@Builder
class Person{
    private final String name;
    private int age;
}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Person person = new Person("홍길동", 20);
        person = new Person("고길동");  // final name > 반드시 이름은 들어가야함
        
        person = Person.builder().name("홍길동").age(25).build();
    }
}